apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-web-regular
  name: deploy-web-regular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-web-regular
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-web-regular
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: app-conf
          mountPath: /etc/nginx/conf.d
        resources: {}
      volumes:
      - name: app-conf
        configMap:
          name: nginx-configmap
status: {}
