apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rolebinding_prod_admin
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role_prod_admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: prod_admin